### ISSUE TITLE
Reloading web server configuration

### ISSUE THREAD

**Issue by vegardx** [schubergphilis/letsencrypt#2]
Hi,

This looks very good, but have any thought been given to how to best make sure that the web servers configuration is reloaded when the certificate is updated?

**Comment by thoutenbos** [comment]
Hello,

Yes, the provider uses inline resources so that you can notify on any changes (like updating the certificate) to reload your webserver. An example of this is also in the text cookbook:

https://github.com/schubergphilis/letsencrypt/blob/master/test/fixtures/cookbooks/acme_client/recipes/default.rb#L48

Best,
Thijs

**Comment by vegardx** [comment]
Doh! So simple I didn't think about it.
